spring:
  application:
    name: Config-Prod
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    eureka-server-u-r-l-context: http://localhost:8761/eureka
